var dateformats = [
{'locale': 'ar', 'dateformat': 'dd/MM/yy'},
{'locale': 'eu', 'dateformat': 'M/d/yy'},
{'locale': 'ca_ES', 'dateformat': 'dd/MM/yy'},
{'locale': 'zh_CN', 'dateformat': 'yy-M-d'},
{'locale': 'zh_TW', 'dateformat': 'yyyy/M/d'},
{'locale': 'nl_NL', 'dateformat': 'd-M-yy'},
{'locale': 'en_AU', 'dateformat': 'd/MM/yy'},
{'locale': 'en_NZ', 'dateformat': 'd/MM/yy'},
{'locale': 'en_ZA', 'dateformat': 'yyyy/MM/dd'},
{'locale': 'en_GB', 'dateformat': 'dd/MM/yy'},
{'locale': 'en_US', 'dateformat': 'M/d/yy'},
{'locale': 'fr_CA', 'dateformat': 'yy-MM-dd'},
{'locale': 'fr_FR', 'dateformat': 'dd/MM/yy'},
{'locale': 'ja_JP', 'dateformat': 'yy/MM/dd'},
{'locale': 'ko_KR', 'dateformat': 'yy. M. d'},
{'locale': 'mn', 'dateformat': 'M/d/yy'},
{'locale': 'pt_BR', 'dateformat': 'dd/MM/yy'},
{'locale': 'pt_PT', 'dateformat': 'dd-MM-yyyy'},
{'locale': 'ru_RU', 'dateformat': 'dd.MM.yy'},
{'locale': 'es_MX', 'dateformat': 'd/MM/yy'},
{'locale': 'es_ES', 'dateformat': 'd/MM/yy'},
{'locale': 'sv_SE', 'dateformat': 'yyyy-MM-dd'},
{'locale': 'tr_TR', 'dateformat': 'dd.MM.yyyy'},
{'locale': 'vi_VN', 'dateformat': 'dd/MM/yyyy'},
];
